Assignment 2/Showroom/urls.py
from django.urls import path
from .views import Home, Team, BrandDetail

urlpatterns = [
    path("", Home, name="Home"),
    path("team/", Team, name="Team"),
    path("brand-detail/<int:id>", BrandDetail, name="BrandDetail"),
]

Assignment 2/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("showroom/", include("Showroom.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Assignment 2/Showroom/models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from uuid import uuid4
from django.core.files.storage import FileSystemStorage

fs = FileSystemStorage(location=settings.MEDIA_ROOT)


def user_directory_path(instance, filename):
    ext = filename.split("-")[-1]

    return "{0}.{1}".format(uuid4(), ext)


class Brand(models.Model):
    name = models.CharField(max_length=50, verbose_name="Brand")
    image = models.ImageField(upload_to=user_directory_path, default="")

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Showroom(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    brand = models.ManyToManyField(
        Brand,  default="")

    created_at = models.DateTimeField(
        auto_now_add=True)

    def __str__(self):
        return self.name


class Staff(models.Model):
    name = models.CharField(max_length=50)
    phone_number = models.PositiveIntegerField()
    showroom = models.ForeignKey(
        Showroom, on_delete=models.CASCADE, null=False, )
    image = models.ImageField(upload_to=user_directory_path,default="")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Joining Date")

    def __str__(self):
        return self.name


class Model(models.Model):
    name = models.CharField(max_length=50, verbose_name="Model")
    brand = models.ForeignKey(
        Brand, on_delete=models.CASCADE, null=False, default="")

    def __str__(self):
        return self.name


class Engine(models.Model):
    name = models.CharField(max_length=50, verbose_name="Engine")
    model = models.OneToOneField(Model, on_delete=models.CASCADE, default="")

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Feature(models.Model):
    name = models.CharField(max_length=50)
    model = models.ManyToManyField(Model)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Car(models.Model):
    name = models.CharField(max_length=50)

    image = models.ImageField(upload_to=user_directory_path, default="")

    showroom = models.ForeignKey(
        Showroom, on_delete=models.CASCADE, null=False)
    brand = models.ForeignKey(
        Brand, on_delete=models.CASCADE, null=False)
    model = models.ForeignKey(
        Model, on_delete=models.CASCADE, null=False, default="")

    stock = models.PositiveIntegerField()

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

Assignment 2/Showroom/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from .models import Brand, Car, Engine, Model, Staff

# Create your views here.


def Home(request: HttpRequest):
    brands = Brand.objects.all()
    return render(request, "Home.html", {"brands": brands})


def Team(request: HttpRequest):
    staffs = Staff.objects.all()
    return render(request, "Team.html", {"staffs": staffs})


def BrandDetail(request: HttpRequest, id: int = None):
    brand = Brand.objects.get(id=id)
    cars = Car.objects.filter(brand=id)

    for car in cars:

        engine = Engine.objects.filter(model=car.model.id)
        if (engine.count() > 0):

            car.engine = engine[0]

    return render(request, "BrandDetail.html", {"brand": brand, "cars": cars})

Assignment 2/Showroom/templates/Base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title%}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include "Header.html" %} {% block content %} {% endblock content %}
    {%include "Footer.html" %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

Assignment 2/Showroom/templates/BrandDetail.html
{% extends 'Base.html' %} 
{% block title %}Brand Detail | Showroom {% endblock %}
{% block content %} 
<div class="container mt-5">
  <div class="mb-5" style="text-align: center; margin-bottom: 20px">
    <h2> {{brand.name}} </h2>
    <p>Discover Our Car Models and Features</p>
  </div>

  <div class="row">
    {% for car in cars %}
    <div class="col-md-4">
      <div
        style="
          border: none;
          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
          margin-bottom: 20px;
        "
      >
        <img
          src="{{car.image.url}}"
          alt="Car Image"
          style="height: auto;width:100%; object-fit: contain"
        />
        <div style="padding: 15px">
          <h5 style="font-size: 1.25rem; font-weight: bold; margin-top: 10px">
            {{car.name}}
          </h5>
          <p style="margin-top: 5px"><strong>Model:</strong> {{car.model}}</p>
          <p style="margin-top: 5px"><strong>Engine:</strong> {{car.engine}}</p>
          <p style="margin-top: 5px">
            <strong>Features:</strong> 
            <ul>
            {% for feature in car.model.feature_set.all %}
                <li> {{feature}} </li>
            {% endfor %}
            </ul>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
    
  </div>
</div>
{% endblock content %}

Assignment 2/Showroom/templates/Footer.html
<footer style="background-color: #333; color: white" class="py-4">
  <div class="container text-center">
    <p>&copy; 2023 Waseem M. All rights reserved.</p>
  </div>
</footer>

Assignment 2/Showroom/templates/Header.html
<header class="bg-dark text-white py-4">
  <div class="container">
    <div class="row justify-content-between align-items-center">
      <div class="col-md-6">
        <h1 class="mb-0">Showroom</h1>
      </div>
      <div class="col-md-6 text-md-right">
        <nav class="nav">
          <a class="nav-link text-white" href="{% url 'Home' %}">Home</a>
          <a class="nav-link text-white" href="{% url 'Team' %}">Our Team</a>
        </nav>
      </div>
    </div>
  </div>
</header>

Assignment 2/Showroom/templates/Home.html
{% extends 'Base.html' %}
{% block title %}Showroom | Home{% endblock title %}
{% block content %}
<div class="container mt-5" style="min-height:70vh" >
    <div class="row">
        {% for brand in brands %}
        <div class="col-md-4 mb-4">
            <div class="card" style="border: none; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
              <img src="{{brand.image.url}}" alt="Card Image" class="card-img-top" style="border-top-left-radius: 10px; border-top-right-radius: 10px; height:250px;width:auto; object-fit: contain;background-color:#000000;">
              <div class="card-body">
                <h5 class="card-title" style="margin-top: 10px; font-size: 1.25rem; font-weight: bold;">{{brand.name}}</h5>
                <a href="{% url 'BrandDetail' brand.id %}" class="btn btn-primary mt-4" style="border-radius: 5px;">Details</a>
              </div>
            </div>
          </div>
      {% endfor %}

      
    </div>
  </div>
{% endblock content %}

Assignment 2/Showroom/templates/Team.html
{% extends 'Base.html' %} {% block title %}Showroom | Our Team{% endblock title%} 
{% block content %}
<div class="container mt-5" style="min-height: 70vh">
  <div class="row">
    {% for staff in staffs %}
    <div class="col-md-4 mb-4">
      <div
        class="card"
        style="
          border: none;
          border-radius: 10px;
          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        "
      >
        <img
          src="{{staff.image.url}}"
          alt="Card Image"
          class="card-img-top"
          style="
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
            height: 250px;
            width: auto;
            object-fit: contain;
            background-color: #000000;
          "
        />
        <div class="card-body">
          <h5
            class="card-title"
            style="margin-top: 10px; font-size: 1.25rem; font-weight: bold"
          >
            {{staff.name}}
          </h5>
          <div>

              
              <strong style="font-weight:500" class="mt-5" >
                  Showroom: <span style="font-weight:300" > {{staff.showroom}}</span>
                </strong>
            </div>
            <div>
                <strong style="font-weight:500">
                    Joining date: <span style="font-weight:300" > {{staff.created_at}}</span>
                </strong>
            </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}